<a href="https://colab.research.google.com/github/miriammedel/Examen-Pr-ctico/blob/master/iris_neural_net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Los cambios realizados en la arquitectura y los parámetros son:**

*   Se agregaron más neuronas a la primera capa densa (16 en lugar de 10) y se agregó una capa densa adicional (8 neuronas).
*   La función de activación de la primera capa densa se cambió de 'sigmoid' a 'relu'.
* La función de activación de la capa de salida se cambió de 'sigmoid' a 'softmax'.
*El tamaño del batch se redujo a 10 (anteriormente era 50).


En general, estos cambios permiten que la red neuronal tenga una mayor capacidad para aprender patrones en los datos de entrada. Además, la función de activación 'softmax' en la capa de salida es más adecuada para problemas de clasificación multiclase, ya que produce una distribución de probabilidad sobre las diferentes clases de salida. Al reducir el tamaño del batch, se puede mejorar el proceso de optimización al actualizar los pesos con más frecuencia y, por lo tanto, mejorar el aprendizaje de la red.

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [ ]:
dataFile = open("iris.csv")
print(dataFile)

<_io.TextIOWrapper name='iris.csv' mode='r' encoding='UTF-8'>


In [ ]:
df = pd.read_csv(dataFile)
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [ ]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [ ]:
print(X[0:5])
print(y[0:5])

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [ ]:
print(X.shape)
print(y.shape)

(149, 4)
(149,)


In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [ ]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [ ]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
print(X_train[0:5])

[[5.2 3.4 1.4 0.2]
 [5.1 2.5 3.  1.1]
 [6.2 2.9 4.3 1.3]
 [5.9 3.2 4.8 1.8]
 [5.1 3.8 1.5 0.3]]


In [ ]:
print(y_train[0:5])

[[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


In [ ]:
print(X_test[0:5])

[[6.1 2.6 5.6 1.4]
 [6.5 3.2 5.1 2. ]
 [5.  2.  3.5 1. ]
 [5.5 2.4 3.7 1. ]
 [4.4 2.9 1.4 0.2]]


In [ ]:
print(y_test[0:5])

[[0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(4,)),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

In [ ]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, batch_size=10, epochs=100, verbose=0)

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.12479904294013977
Test accuracy: 1.0


In [ ]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 114ms/step


array([[2.5674188e-05, 1.1851616e-01, 8.8145816e-01],
       [3.6967959e-04, 3.6622867e-01, 6.3340163e-01],
       [7.5462316e-03, 7.8474534e-01, 2.0770845e-01],
       [1.4409353e-02, 9.0725815e-01, 7.8332655e-02],
       [9.7681397e-01, 2.3185445e-02, 5.7915986e-07],
       [1.0155795e-06, 4.1291233e-02, 9.5870775e-01],
       [8.1462429e-05, 2.0122801e-01, 7.9869062e-01],
       [1.0828682e-02, 8.7457407e-01, 1.1459723e-01],
       [2.5116193e-05, 1.0874675e-01, 8.9122808e-01],
       [1.2528768e-02, 8.8535500e-01, 1.0211625e-01],
       [9.8025656e-01, 1.9743286e-02, 2.2777681e-07],
       [9.7605735e-01, 2.3942107e-02, 4.2793343e-07],
       [3.7229310e-03, 7.3875517e-01, 2.5752190e-01],
       [9.6734756e-01, 3.2651886e-02, 5.8125454e-07],
       [9.8384368e-01, 1.6156144e-02, 2.7093191e-07],
       [3.3539865e-04, 4.0033790e-01, 5.9932661e-01],
       [2.1411077e-05, 1.1065692e-01, 8.8932168e-01],
       [7.1757096e-03, 9.1002905e-01, 8.2795247e-02],
       [9.9195677e-01, 8.043

In [ ]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 2 1 1 0 2 2 1 2 1 0 0 1 0 0 2 2 1 0 0 0 0 1 0 1 1 1 0 0 2]
Predicted: [2 2 1 1 0 2 2 1 2 1 0 0 1 0 0 2 2 1 0 0 0 0 1 0 1 1 1 0 0 2]
